version: "2.4"

services:

  droppy:
    container_name: droppy
    restart: always
    build: droppy
    volumes:
      - files:/files
    ports:
      - "80:80"

  watcher:
    container_name: watcher
    restart: always
    build: watcher
    volumes:
      - files:/files
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  files:        
